In [28]:
import numpy as np
import sympy as sp
import itertools

In [29]:
#2×2
mat2 = np.matrix([[1,3],[4,3]])
E2 = np.eye(2)
eigen = sp.Symbol('eigen')

mat = mat2 - eigen*E2
det_mat = mat[0,0]*mat[1,1] - mat[0,1]*mat[1,0]

eigen_list = sp.solve(det_mat)

print(mat2)
print(eigen_list)

[[1 3]
 [4 3]]
[-1.60555127546399, 5.60555127546399]


In [30]:
#3×3
mat3 = np.matrix([[1,3,2],[3,-1,6],[5,2,1]])
E3 = np.eye(3)

mat = mat3 - eigen*E3

b = [0,1,2]
det_mat = 0
for i,j,k in itertools.product(b,b,b):
    det_mat = det_mat + sp.LeviCivita(i,j,k)*mat[0,i]*mat[1,j]*mat[2,k]

eigen_list = sp.solve(det_mat)
print(mat3)
print(eigen_list)

[[ 1  3  2]
 [ 3 -1  6]
 [ 5  2  1]]
[7.19074630495270, -3.09537315247635 - 1.71311154457811*I, -3.09537315247635 + 1.71311154457811*I]
